---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- $clusterrolebindingname := print .Values.projectName "-" .Values.clusterRoleBinding.name }}
  name: {{ $clusterrolebindingname }}
subjects:
- kind: ServiceAccount
  {{- $serviceaccountname := print  .Values.projectName "-" .Values.serviceAccount.name }}
  name: {{ $serviceaccountname }}
  namespace: {{ .Values.nameSpace }}
roleRef:
  kind: ClusterRole
  {{- $clusterrolename := print .Values.projectName "-" .Values.clusterRole.name }}
  name: {{ $clusterrolename }}
  apiGroup: rbac.authorization.k8s.io