---
apiVersion: v1
kind: Secret
metadata:
  {{- $secretname := print .Values.projectName "-" .Values.secretToken.name }}
  name: {{ $secretname }}
  annotations:
    {{- $serviceaccountname := print .Values.projectName "-" .Values.serviceAccount.name }}
    kubernetes.io/service-account.name: {{ $serviceaccountname }}
type: kubernetes.io/service-account-token
  
