---
apiVersion: v1
kind: Service
metadata:
  {{- $servicename := print .Values.projectName "-" .Values.service.name }}
  name: {{ $servicename }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- range $key, $value := .Values.pod.labels }}
      {{ $key}}: {{ $value }}
    {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}