---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  serviceAccountName: mysac
  containers:
  - name: flask-app
    image: pokhriyalindock/gke:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8080